name: CI/CD Build & Deploy (Harbor devops)

on:
  push:
    branches: ["main"]
    paths:
      - "Backend-SmartVetSystem/**"
      - ".github/workflows/**"
      - "docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Harbor
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          IMAGE=${{ secrets.REGISTRY_URL }}/devops/smartvet-backend
          docker build -t ${IMAGE}:latest ./Backend-SmartVetSystem
          docker tag ${IMAGE}:latest ${IMAGE}:${{ github.sha }}

      - name: Push image
        run: |
          IMAGE=${{ secrets.REGISTRY_URL }}/devops/smartvet-backend
          docker push ${IMAGE}:latest
          docker push ${IMAGE}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy on EC2
        run: |
          IMAGE=${{ secrets.REGISTRY_URL }}/devops/smartvet-backend
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            set -e
            sudo docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }};
            sudo docker pull ${IMAGE}:latest;
            sudo docker stop smartvet-backend || true;
            sudo docker rm smartvet-backend || true;
            sudo docker run -d --name smartvet-backend \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              --env-file /opt/smartvet/.env\
              --restart=always \
              ${IMAGE}:latest;
          "
